# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  # - repo: https://github.com/pre-commit/mirrors-mypy  # python static code analysis, uses type hinting
  #   rev: v1.11.0
  #   hooks:
  #     - id: mypy
  #       exclude: test_*
  #       args:
  #         [
  #           # --strict,
  #           # --ignore-missing-imports
  #           --config-file=pyproject.toml,
  #           # --no-warn-no-return,
  #           # --show-error-codes,
  #           # --check-untyped-defs,
  #         ]
  #       additional_dependencies: [pydantic, types-requests, types-redis, types-PyYAML==6.0.0] # add if use pydantic

  # - repo: local
  #   hooks:
  #   - id: pytest
  #     name: pytest
  #     # entry: /Users/noamg/Library/Caches/pypoetry/virtualenvs/daputils-DeUZdhh3-py3.11/bin/pytest -v
  #     # entry: ${poetry env info --path}/bin/pytest -v
  #     # entry: poetry run pytest -v -m PreCommitTests
  #     # language: system
  #     entry: ./pytest_run.sh
  #     language: script
  #     pass_filenames: false
  #     # alternatively you could `types: [python]` so it only runs when python files change
  #     # though tests might be invalidated if you were to say change a data file
  #     always_run: true
