[package]
name = "bedtools"
version = "0.1.0"
edition = "2021"

[dependencies.noodles]
features = ["bed", "core", "vcf", "bgzf"]
# version = "0.79.0"
path = "../../third_party/noodles/noodles"

[dependencies]
anyhow = "1.0.86"
rusqlite = "0.32.1"
