name: "Get ugbio members"
description: "utilty action to dynamically get the workspaces under ugbio-utils"

outputs:
    members:
      description: "Members list"
      value: ${{ steps.list_members.outputs.matrix }}

runs:
  using: "composite"

  steps:

  - id: list_members
    shell: bash
    run: |
      matrix=$(python3 ${GITHUB_WORKSPACE}/.github/utils/ugbio_members_matrix.py)
      {
        echo 'matrix<<EOF'
        echo ${matrix}
        echo EOF
      } >> ${GITHUB_OUTPUT}
