 
name: "Update devcontainer jsons"
description: "Update docker image version in all devcontainer jsons"

inputs:
 version:
    description: "new version"
    required: true
 ref:
    description: "git ref"
    required: false
    default: ""
 git-token:
    description: "github token"
    required: true

outputs:
  commit-sha:
      description: "Update commit (long) sha"
      value: m${{ steps.commit-and-push.outputs.commit_long_sha }}

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        token: ${{ inputs.git-token }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install json5

    - name: Update devcontainer files with new docker image
      shell: bash
      run: python .github/utils/update_devcontainer.py --version ${{ inputs.version }}

    - name: Fix file permissions
      shell: bash
      run: |
        find . -path ./.git -prune -o -exec chmod u+rw {} \;

    - name: Commit and push changes
      id: commit-and-push
      uses: EndBug/add-and-commit@v9
      with:
        message: Update docker images in devcontainer jsons to ${{ inputs.version }}
        committer_name: GitHub Actions
        committer_email: actions@github.com