[project]
name = "ugbio_hla_la"
version = "1.2.1-0dev-47"
description = "Ultima Genomics hla-la"
authors = [
    { name = "Maya Levy", email = "maya.levy@ultimagen.com" },
    { name = "Avigail Moldovan", email = "avigail.moldovan@ultimagen.com" },
]
readme = "README.hla_la.md"

[project.license]
text = "Apache-2.0"

[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"
