
name: "Update workspaces version"
description: "Update version in pyproject.toml in all workspaces and commit changes"

inputs:
 version:
    description: "new version"
    required: true
 ref:
    description: "git ref"
    required: false
 git-token:
    description: "github token"
    required: true

outputs:
  commit-sha:
      description: "Update commit (long) sha"
      value: ${{ steps.commit-and-push.outputs.commit_long_sha }}

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        token: ${{ inputs.git-token }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install tomli_w

#    - name: Ensure clean repository state
#      shell: bash
#      run: |
#        git reset --hard
#        git clean -fd

    - name: Update pyproject.toml files with new dev_version
      shell: bash
      run: python .github/utils/update_project_version.py ${{ inputs.version }}

    - name: Fix file permissions
      shell: bash
      run: |
        sudo chmod -R ugo+rwX .

#    - name: Debug permissions
#      shell: bash
#      run: |
#        echo "Checking permissions and ownership:"
#        git status
#        ls -l src/omics/pyproject.toml
#        ls -l src/cnv/pyproject.toml
#        ls -l src/ppmseq/pyproject.toml
#        ls -ld .git

    - name: Commit and push changes
      id: commit-and-push
      uses: EndBug/add-and-commit@v9
      with:
        message: Update pyproject.toml versions to ${{ inputs.version }}
        committer_name: GitHub Actions
        committer_email: actions@github.com
