 
name: "Update workspaces version"
description: "Update version in pyproject.toml in all workspaces and commit changes"

inputs:
 version:
    description: "new version"
    required: true
 ref:
    description: "git ref"
    required: false
 git-token:
    description: "github token"
    required: true
 push:
    description: "push changes"
    type: boolean
    default: true
    required: false

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: 0
        token: ${{ inputs.git-token }}
        clean: true
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install tomli_w

    - name: Update pyproject.toml files with new dev_version
      shell: bash
      run: python .github/utils/update_project_version.py ${{ inputs.version }}

    - name: Verify file ownership
      shell: bash
      run: ls -l

    - name: Fix file permissions
      shell: bash
      run: |
        find . -path ./.git -prune -o -exec chmod u+rw {} \;

    # - name: Mark repository as safe
    #   run: git config --global --add safe.directory $(pwd)

    - name: Remove Git object database locks
      shell: bash
      run: |
        rm -f .git/index.lock
        rm -f .git/refs/heads/main.lock

    - name: Check Git status
      shell: bash
      run: git status

    - name: Commit changes manually
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -am "Update pyproject.toml versions to ${{ inputs.version }}"
        git push

    # - name: Commit changes
    #   shell: bash
    #   run: |
    #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
    #     git config --local user.name "github-actions[bot]"
    #     git commit -am "Update pyproject.toml versions to ${{ inputs.version }}"
    #     git status
    #     git push
    # - name: Commit changes
    #   uses: EndBug/add-and-commit@v9
    #   with:
    #     message: Update pyproject.toml versions to ${{ inputs.version }}
    #     committer_name: GitHub Actions
    #     committer_email: actions@github.com

    # - name: Push changes
    #   if: inputs.push
    #   uses: ad-m/github-push-action@master
    #   with:
    #     branch: ${{ inputs.ref }}
