name: "Get ugbio workspaces"
description: "utilty action to dynamically get the workspaces under ugbio-utils"

inputs:
    remove-internal-dockers:
      description: "whether to filter out internal docker that used only for tests"
      type: boolean
      required: true

outputs:
    workspaces: 
      description: "Workspaces list"
      value: ${{ steps.list_dirs.outputs.matrix }}

runs:
  using: "composite"

  steps:
  - name: Filter out internal dockers members
    shell: bash
    if: ${{ inputs.remove-internal-dockers == 'true' }}
    run: echo "EXCLUDE_FOLDERS=("omics", "core")" >> ${GITHUB_ENV}

  - name: Do not filter out internal dockers members
    shell: bash
    if: ${{ inputs.remove-internal-dockers == 'false' }}
    run: echo "EXCLUDE_FOLDERS=("dummy")" >> ${GITHUB_ENV} #some non exiting folder

  - id: list_dirs
    shell: bash
    run: |
      folders_to_filter_out=${{ env.EXCLUDE_FOLDERS }}
      filter_pattern=$(printf "|%s" "${folders_to_filter_out[@]}")
      filter_pattern="${filter_pattern:1}"  # Remove the leading "|"
      echo "::set-output name=matrix::$(ls src   | grep -v "__" | grep -v "/\." | grep -Ev "$filter_pattern" | sed 's|src/||' | jq -R -s -c 'split("\n")[:-1]')"