name: "Run ugbio workspace tests"
description: "general action to build and run test of ugbio workspace"

inputs:
  workspace-folder:
    description: "workspace folder under src"
    required: true
  docker-file:
    description: "Dockerfile path"
    required: true
  docker-context:
    description: "Docker build context"
    required: true
    default: "."

runs:
  using: "composite"

  steps:
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v3
    #   with:
    #     role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/${{ env.AWS_ROLE_NAME }}
    #     aws-region: ${{ env.AWS_REGION }}

    # - name: Login to Amazon ECR
    #   id: ecr-login
    #   uses: aws-actions/amazon-ecr-login@v1


    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

    - name: Login to GCR
      id: gcr-login
      uses: docker/login-action@v2
      with:
        registry: us-central1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: image=moby/buildkit:latest

    - name: Build docker
      uses: docker/build-push-action@v4
      with:
        file: ${{ inputs.docker-file }}
        context: ${{ inputs.docker-context }}
        provenance: false
        load: true
        push: false
        tags: ${{ inputs.workspace-folder }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run tests in the container
      shell: bash
      run: |
        docker run --rm -v ${{ github.workspace }}/src:/workdir/src ${{ inputs.workspace-folder }} pytest /workdir/src/${{ inputs.workspace-folder }}

    #todo how to upload results?
    #      - name: Upload Test Results
    #        if: always()
    #        uses: actions/upload-artifact@v3
    #        with:
    #          name: ${{ inputs.workspace-folder }}-test-results
    #          path: src/${{ inputs.workspace-folder }}
