name: "Run ugbio workspace tests"
description: "general action to build and run test of ugbio workspace"

inputs:
  workspace-folder:
    description: "workspace folder under src"
    required: true
  docker-file:
    description: "Dockerfile path (from repository root)"
    required: true
  docker-context:
    description: "Docker build context"
    required: false
    default: "."
  aws-account:
    description: "AWS account id"
    required: true
  aws-region:
    description: "AWS region"
    required: true
  aws-role-name:
    description: "AWS role name"
    required: true
  ugbio_base_image:
      description: "ugbio_base image"
      required: true

runs:
  using: "composite"

  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account }}:role/${{ inputs.aws-role-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build docker
      uses: docker/build-push-action@v6
      with:
        file: ${{ inputs.docker-file }}
        context: ${{ inputs.docker-context }}
        provenance: false
        load: true
        push: false
        tags: ${{ inputs.workspace-folder }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: BASE_IMAGE=${{ steps.ecr-login.outputs.registry }}/${{ inputs.ugbio_base_image }}

    - name: Run python tests (if exist) in the container
      working-directory: src/${{ inputs.workspace-folder }}
      shell: bash
      run: docker run --rm -v .:/home/ugbio/src ${{ inputs.workspace-folder }} run_tests /home/ugbio/src || [ $? -eq 5 ]
