config:
  EMR_CLUSTER_NAME: "hail-cluster-the-real-thing" # Give a name to your EMR cluster
  EC2_NAME_TAG: "hail-EMR-3000" # Adds a tag to the individual EC2 instances
  OWNER_TAG: "GilHail3000Gvcfs" # EC2 owner tag
  PROJECT_TAG: "BIOIN-2151" # Project tag
  REGION: "us-east-1"
  MASTER_INSTANCE_TYPE: "r5.4xlarge"
  WORKER_INSTANCE_TYPE: "r5.4xlarge"
  WORKER_INSTANCE_TYPE_2: "m5.4xlarge"
  WORKER_ON_DEMAND_COUNT: "4" # Number of worker on demand nodes
  WORKER_SPOT_COUNT: "20" # Number of type 1 spot worker nodes
  WORKER_SPOT_COUNT_2: "10" # Number of type 2 spot worker nodes
#  WORKER_BID_PRICE: "0.44" # Required for spot instances
  WORKER_BID_PRICE: "1" # todo for tests use large number
  MASTER_HD_SIZE: "1000" # Size in GB - For large data sets, more HD space may be required
  WORKER_HD_SIZE: "500" # Size in GB - For large data sets, more HD space may be required
  SUBNET_ID: "" # This field can be either left blank or for further security you can specify your private subnet ID in the form: subnet-1a2b3c4d
  S3_BUCKET: "s3n://ultima-bucket-logs-all/" # Specify your S3 bucket for EMR log storage
  KEY_NAME: "aultima" # Input your key name ONLY! DO NOT include the .pem extension
  PATH_TO_KEY: "/Users/avigailmoldovan/.ssh/" # Full path to the FOLDER where the .pem file resides
  WORKER_SECURITY_GROUP: "" # If empty creates a new group by default. You can also add a specific SG. See the SG link in the FAQs section
  MASTER_SECURITY_GROUP: "" # If empty creates a new group by default. You can also add a specific SG. See the SG link in the FAQs section
  HAIL_VERSION: "" # Specify a git hash version (the first 7-12 characters will suffice) to install a specific commit/version. When left empty or "current" will install the latest version of Hail available in the repo
