name: Build ug-cnmops docker
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "Docker image tag, If omitted will use github short sha"
        required: false
        type: string

permissions:
  id-token: write # Required for assuming an AWS role
  contents: read # Required for actions/checkout

jobs:
  build-cnmops-docker:
    uses: ./.github/workflows/build-workspace-docker.yml
    secrets: inherit
    with:
      workspace-folder: cnv
      docker-file: src/cnv/Dockerfile
      docker-image: ug_cnv
      docker-tag: ${{ inputs.image-tag }}