name: Build ugbio_vcflite docker
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "Docker image tag, If omitted will use github short sha"
        required: false
        type: string

permissions:
  id-token: write # Required for assuming an AWS role
  contents: read # Required for actions/checkout

jobs:
  build-docker:
    uses: ./.github/workflows/build-workspace-docker.yml
    secrets: inherit
    with:
      workspace-folder: vcflite
      docker-file: src/vcflite/Dockerfile
      docker-image: ugbio_vcflite
      docker-tag: ${{ inputs.image-tag }}