name: CI

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"      # every midnight (UTC)
  workflow_dispatch:

permissions:
  id-token: write # Required for assuming an AWS role
  contents: read # Required for actions/checkout

env:
  AWS_REGION: us-east-1
  AWS_ROLE_NAME: github-actions-ecr
  AWS_ACCOUNT: 337532070941
  UGBIO_BASE_IMAGE_NAME: ugbio_base:1.7.0
  UGBIO_UTILS_REPO_PATH: ./ugbio-utils
  INSTALL_BIO_PATH: ./install-bio
  INSTALL_BIO_REF: main
  INSTALL_BIO_SCRIPT: install-bio.sh

jobs:
  get-members:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_members.outputs.members}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/get-members
        id: list_members
#        with:
#          keep-internal-dockers: true

  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        # Install a specific version of uv.
        version: "0.4.17"

    - name: Run pre-commit
      run: |
        uv run pre-commit install
        uv run pre-commit run --all-files

  Trivy-docker-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy to scan Dockerfile
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'config'
          scan-ref: './'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  Trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy to scan fs
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  ugbio-utils-CI:
    runs-on: ubuntu-latest
    needs: [get-members]
    strategy:
      fail-fast: false
      matrix:
        module: ${{fromJson(needs.get-members.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Run workspace tests
      uses: ./.github/actions/run-workspace-tests
      with:
        workspace-folder: ${{ matrix.module }}
        docker-file: src/${{ matrix.module }}/Dockerfile
        aws-account: ${{ env.AWS_ACCOUNT }}
        aws-region: ${{ env.AWS_REGION }}
        aws-role-name: ${{ env.AWS_ROLE_NAME }}
        ugbio_base_image: ${{ env.UGBIO_BASE_IMAGE_NAME }}

  ugbio-utils-bioinfo-CI:
    runs-on: build-docker-4
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          path: ${{ env.UGBIO_UTILS_REPO_PATH }}

      - name: Checkout install-bio repo
        uses: actions/checkout@v4
        with:
          repository: Ultimagen/install-bio
          ref: ${{ env.INSTALL_BIO_REF }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          path: ${{ env.INSTALL_BIO_PATH }}

      - name: run install-bio.sh
        run: |
          bash ${{ env.INSTALL_BIO_PATH }}/${{ env.INSTALL_BIO_SCRIPT }}

      - name: install ugbio-utils venv
        working-directory: ${{ env.UGBIO_UTILS_REPO_PATH }}
        run: uv sync --all-extras --all-packages

      - name: run tests
        working-directory: ${{ env.UGBIO_UTILS_REPO_PATH }}
        run: |
          export PATH=/home/linuxbrew/.linuxbrew/bin/:$PATH
          uv run cnvpytor -download #needed for test_run_cnvpytor
          uv run pytest --durations=0 src/ --ignore src/cnv/cnmops
