name: CI

on: [pull_request]

permissions:
  id-token: write # Required for assuming an AWS role
  contents: read # Required for actions/checkout

env:
  AWS_REGION: us-east-1
  AWS_ROLE_NAME: github-actions-ecr
  AWS_ACCOUNT: 337532070941
  UGBIO_BASE_IMAGE_NAME: ugbio_base:1.0

jobs:
  get-workspaces:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:
      - uses: actions/checkout@v2
      - id: list_dirs
        run: echo "::set-output name=matrix::$(ls src   | grep -v "__" | grep -v "/\." | sed 's|src/||' | jq -R -s -c 'split("\n")[:-1]')"
  ugbio-utils-CI:
    runs-on: ubuntu-latest
    needs: [get-workspaces]
    strategy:
      fail-fast: false
      matrix:
        module: ${{fromJson(needs.get-workspaces.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Run workspace tests
      uses: ./.github/actions/run-workspace-tests
      with:
        workspace-folder: ${{ matrix.module }}
        docker-file: src/${{ matrix.module }}/Dockerfile
        aws-account: ${{ env.AWS_ACCOUNT }}
        aws-region: ${{ env.AWS_REGION }}
        aws-role-name: ${{ env.AWS_ROLE_NAME }}
        ugbio_base_image: ${{ env.UGBIO_BASE_IMAGE_NAME }}



