name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Run cnv tests
        uses: ./.github/actions/run-workspace-tests
        with:
          workspace-folder: cnv
          docker-file: src/cnv/Dockerfile
      
      - name: Run single cell tests
        uses: ./.github/actions/run-workspace-tests
        with:
          workspace-folder: single_cell
          docker-file: src/single_cell/Dockerfile



