name: CI

on: [pull_request]

jobs:
  ugbio-utils-CI:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
        - core
        - cnv
        - single_cell
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Run workspace tests
      uses: ./.github/actions/run-workspace-tests
      with:
        workspace-folder: ${{ matrix.module }}
        docker-file: src/${{ matrix.module }}/Dockerfile



