name: CI

on: [pull_request]

permissions:
  id-token: write # Required for assuming an AWS role
  contents: read # Required for actions/checkout

env:
  AWS_REGION: us-east-1
  AWS_ROLE_NAME: github-actions-ecr
  AWS_ACCOUNT: 337532070941
  UGBIO_BASE_IMAGE_NAME: ugbio_base:1.2.0

jobs:
  get-members:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_members.outputs.members}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/get-members
        id: list_members
        with:
          keep-internal-dockers: true

  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        # Install a specific version of uv.
        version: "0.4.17"

    - name: Run pre-commit
      run: |
        uv run pre-commit install
        uv run pre-commit run --all-files

  ugbio-utils-CI:
    runs-on: ubuntu-latest
    needs: [get-members]
    strategy:
      fail-fast: false
      matrix:
        module: ${{fromJson(needs.get-members.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Run workspace tests
      uses: ./.github/actions/run-workspace-tests
      with:
        workspace-folder: ${{ matrix.module }}
        docker-file: src/${{ matrix.module }}/Dockerfile
        aws-account: ${{ env.AWS_ACCOUNT }}
        aws-region: ${{ env.AWS_REGION }}
        aws-role-name: ${{ env.AWS_ROLE_NAME }}
        ugbio_base_image: ${{ env.UGBIO_BASE_IMAGE_NAME }}
