name: CI

on: [pull_request]

env:
  RYE_VERSION: '0.34.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install bedtools tabix
        run: |
          sudo apt-get update
          sudo apt-get -y install bedtools tabix

      - name: Set up bedops
        run: |
          wget https://github.com/bedops/bedops/releases/download/v2.4.41/bedops_linux_x86_64-v2.4.41.tar.bz2
          tar -xvjf bedops_linux_x86_64-v2.4.41.tar.bz2
          sudo mv bin/* /usr/local/bin/

      - name: Install rye
        uses: eifinger/setup-rye@v3
        with:
          version: ${{ env.RYE_VERSION }}

      - name: Run tests
        run: |
          rye sync
          exit_code=0
          members=$(rye show | awk '/members:/{flag=1; next} /configured sources:/{flag=0} flag' | awk '{print $1}')
          for member in $members; do
            echo "Running tests for $member"
            rye test --package $member || workspace_exit_code=$?
            if [ "$workspace_exit_code" -eq 5 ]; then
              echo "Workspace $member has no tests. Ignoring exit code 5."
            elif [ "$workspace_exit_code" -ne 0 ]; then
              echo "Workspace $member tests failed with exit code $workspace_exit_code."
              exit_code=$workspace_exit_code
            fi
          done
          exit $exit_code

