name: "Increment project version"

on:
  pull_request:
      types: [opened, reopened]
      branches: [ "main" ]

permissions:
  id-token: write
  contents: write
jobs:
  set-dev-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
            length: 7

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
            semver_only: true
            initial_version: "1.0.0"

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-dev-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: prepatch
    
      - uses: ./.github/actions/update-workspaces-version
        with:
          version: ${{ steps.bump-dev-semver.outputs.new_version }}.${{ steps.short-sha.outputs.sha }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

